In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv('../../../data/talkbank/6_0_eigsti_full.csv')
df2 = pd.read_csv('../../../data/talkbank/7_0_nadig_full.csv')
df3 = pd.read_csv('../../../data/talkbank/8_0_flusberg_full.csv')
df4 = pd.read_csv('../../../data/talkbank/9_0_rollins_full.csv')

In [5]:
df = pd.concat([df1, df2, df3, df4])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171 entries, 0 to 20
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          171 non-null    object
 1   age_months    171 non-null    int64
 2   gender        171 non-null    object
 3   group         171 non-null    object
 4   types         171 non-null    object
 5   corpus        171 non-null    object
 6   investigator  171 non-null    object
 7   mlu           171 non-null    float64
 8   filename      171 non-null    object
 9   all_chat      171 non-null    object
 10  child_chat    171 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 16.0+ KB

In [6]:
df.reset_index(drop=True)

,name,age_months,gender,group,types,corpus,investigator,mlu,filename,all_chat,child_chat
0,Adrianne,63,female,ASD,"cross, toyplay, ASD",Eigsti,"Jenny, Inge-Marie, Mother",4.402439,1010,"alright ! you have fun, okay ? okay . alright ...",okay . did you see this ? yeah . xxx let's see...
1,Kate,45,female,TD,"cross, toyplay, ASD",Eigsti,"Inge-Marie, Michelle, Eileen",2.236641,1011,we've got sort of a bumblebee theme here (be)c...,&=counts . &=nods:no . &=nods:yes . &=looks:mo...
2,Dana,56,female,ASD,"cross, toyplay, ASD",Eigsti,"Jenny, Inge-Marie, Mother",1.861244,1012,alright ! yeah &=exhales . and I'm gonna [: go...,xxx . ooh . xxx . &=sings . &=gasps . æh@i ! g...
3,Meredith,40,female,TD,"cross, toyplay, ASD",Eigsti,"Brian, Inge-Marie",3.898477,1013,"did you have fun pointing at all that stuff, M...",yeah . mm@u . &=laughs . ŋŋ@u . &=chuckles . &...
4,Matt,47,male,ASD,"cross, toyplay, ASD",Eigsti,"Inge-Marie, Mother",2.963563,1017,I [!!] ʌ@u [: want] stickers ! I [!!] ʌ@u [: w...,I [!!] ʌ@u [: want] stickers ! I [!!] ʌ@u [: w...
...,...,...,...,...,...,...,...,...,...,...,...
166,Target_Child,39,male,ASD,"long, toyplay, ASD",Rollins,Investigator,1.265823,30500,where would you like to sit ? xxx . [+ trn] ri...,xxx . [+ trn] xxx . [+ trn] xxx . [+ trn] 0 . ...
167,Target_Child,26,male,ASD,"long, toyplay, ASD",Rollins,Investigator,1.000000,30600,I see a car . 0 . I see your car . you found a...,0 . 0 . [+ trn] 0 . 0 . 0 . 0 . 0 . 0 . 0 . 0 ...
168,Target_Child,35,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.005618,30700,let's go this way Chi . bye . bye everybody . ...,bye . bye everybody . bye . bye Chi . see you ...
169,Target_Child,38,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.012397,30800,Chi we needta get a puzzle . where are the puz...,xxx . [+ trn] xxx . [+ trn] xxx . [+ trn] xxx ...
170,Target_Child,41,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.644231,31100,0 [=! gasps] . [+ trn] what's in there ? 0 [=!...,0 . 0 . 0 . 0 . xxx . 0 . yyy . <&-uh oh> [<] ...

In [7]:
df.to_csv('../../../data/talkbank/3_0_eig_nad_flu_rol_merged.csv', index=False)

In [8]:
df['group'].value_counts()

ASD    114
TD      41
DD      16
Name: group, dtype: int64

In [9]:
df['gender'].value_counts()

male      148
female     23
Name: gender, dtype: int64

In [12]:
df5 = pd.concat([df1, df2])
df5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 86 entries, 0 to 37
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          86 non-null     object
 1   age_months    86 non-null     int64
 2   gender        86 non-null     object
 3   group         86 non-null     object
 4   types         86 non-null     object
 5   corpus        86 non-null     object
 6   investigator  86 non-null     object
 7   mlu           86 non-null     float64
 8   filename      86 non-null     int64
 9   all_chat      86 non-null     object
 10  child_chat    86 non-null     object
dtypes: float64(1), int64(2), object(8)
memory usage: 8.1+ KB

In [15]:
df5.reset_index(drop=True)

,name,age_months,gender,group,types,corpus,investigator,mlu,filename,all_chat,child_chat
0,Adrianne,63,female,ASD,"cross, toyplay, ASD",Eigsti,"Jenny, Inge-Marie, Mother",4.402439,1010,"alright ! you have fun, okay ? okay . alright ...",okay . did you see this ? yeah . xxx let's see...
1,Kate,45,female,TD,"cross, toyplay, ASD",Eigsti,"Inge-Marie, Michelle, Eileen",2.236641,1011,we've got sort of a bumblebee theme here (be)c...,&=counts . &=nods:no . &=nods:yes . &=looks:mo...
2,Dana,56,female,ASD,"cross, toyplay, ASD",Eigsti,"Jenny, Inge-Marie, Mother",1.861244,1012,alright ! yeah &=exhales . and I'm gonna [: go...,xxx . ooh . xxx . &=sings . &=gasps . æh@i ! g...
3,Meredith,40,female,TD,"cross, toyplay, ASD",Eigsti,"Brian, Inge-Marie",3.898477,1013,"did you have fun pointing at all that stuff, M...",yeah . mm@u . &=laughs . ŋŋ@u . &=chuckles . &...
4,Matt,47,male,ASD,"cross, toyplay, ASD",Eigsti,"Inge-Marie, Mother",2.963563,1017,I [!!] ʌ@u [: want] stickers ! I [!!] ʌ@u [: w...,I [!!] ʌ@u [: want] stickers ! I [!!] ʌ@u [: w...
...,...,...,...,...,...,...,...,...,...,...,...
81,161,22,female,TD,"cross, toyplay, ASD",Nadig,Mother,1.083333,161,here gonna have some tea ? here's some for you...,0 . 0 . 0 . 0 . xxx . 0 . 0 . 0 . 0 . &=eats ....
82,163,20,male,TD,"cross, toyplay, ASD",Nadig,Mother,1.581081,163,Seeley look . hello . hello . &na call Grandma...,hello . boy that . xxx . hello ? xxx . haha . ...
83,165,20,male,TD,"cross, toyplay, ASD",Nadig,Mother,1.096154,165,"hi &=laughs . oh you wanna talk to Lance, okay...",xxx . hello ? &eh [x 2] . xxx . eidai@b . dode...
84,167,43,female,TD,"cross, toyplay, ASD",Nadig,Mother,5.448276,167,would you open it please ? I can . and they do...,would you open it please ? and they dolls . tw...
85,169,42,male,TD,"cross, toyplay, ASD",Nadig,Mother,3.742424,169,call somebody xxx . who are you calling ? you'...,it &ca fall down . mhm . no . xxx . you can't ...

In [22]:
df5.to_csv('../../../data/talkbank/4_0_eigsti_nadig_merged.csv')

In [11]:
df6 = pd.concat([df3, df4])
df6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85 entries, 0 to 20
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          85 non-null     object
 1   age_months    85 non-null     int64
 2   gender        85 non-null     object
 3   group         85 non-null     object
 4   types         85 non-null     object
 5   corpus        85 non-null     object
 6   investigator  85 non-null     object
 7   mlu           85 non-null     float64
 8   filename      85 non-null     object
 9   all_chat      85 non-null     object
 10  child_chat    85 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 8.0+ KB

In [14]:
df6.reset_index(drop=True)

,name,age_months,gender,group,types,corpus,investigator,mlu,filename,all_chat,child_chat
0,Target_Child,68,male,ASD,"long, toyplay, ASD",Flusberg,Mother,4.127778,30400,you wanna open it ? open . yeah . open . crack...,open . cracker . car . cracker . cracker . cra...
1,Target_Child,70,male,ASD,"long, toyplay, ASD",Flusberg,"Mother, Investigator",4.295522,30610,good boy Stuart . good boy . what's that ? loo...,good boy . shoe . &e [/?] +/. doll . Mikey . M...
2,Target_Child,72,male,ASD,"long, toyplay, ASD",Flusberg,Mother,4.282528,30806,god bless you . bless you . can you sing “sit ...,want water . water . sit down . sit right down...
3,Target_Child,74,male,ASD,"long, toyplay, ASD",Flusberg,Mother,4.948403,30900,roger want some lunch ? want lunch . want some...,want lunch . want some lunch . have some lunch...
4,Target_Child,76,male,ASD,"long, toyplay, ASD",Flusberg,Mother,4.162844,31009,are [/?] you ready Stuart ? huh ? what do you ...,"balloon . momma , I want balloon . balloon . I..."
...,...,...,...,...,...,...,...,...,...,...,...
80,Target_Child,39,male,ASD,"long, toyplay, ASD",Rollins,Investigator,1.265823,30500,where would you like to sit ? xxx . [+ trn] ri...,xxx . [+ trn] xxx . [+ trn] xxx . [+ trn] 0 . ...
81,Target_Child,26,male,ASD,"long, toyplay, ASD",Rollins,Investigator,1.000000,30600,I see a car . 0 . I see your car . you found a...,0 . 0 . [+ trn] 0 . 0 . 0 . 0 . 0 . 0 . 0 . 0 ...
82,Target_Child,35,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.005618,30700,let's go this way Chi . bye . bye everybody . ...,bye . bye everybody . bye . bye Chi . see you ...
83,Target_Child,38,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.012397,30800,Chi we needta get a puzzle . where are the puz...,xxx . [+ trn] xxx . [+ trn] xxx . [+ trn] xxx ...
84,Target_Child,41,male,ASD,"long, toyplay, ASD",Rollins,"Investigator, Camera_Operator",1.644231,31100,0 [=! gasps] . [+ trn] what's in there ? 0 [=!...,0 . 0 . 0 . 0 . xxx . 0 . yyy . <&-uh oh> [<] ...

In [19]:
df6.to_csv('../../../data/talkbank/5_0_flusberg_rollins_merged.csv')